# SQL preparation scripts executed in order by apply_preparation_scripts
# Comment out a line to skip that script
zz_10_convert_charset.sql
zz_20_create_indexes.sql
zz_30_create_FT_indexes.sql
zz_40_fill_FT.sql
#zz_50_repair_FT.sql
# REQUIRED STRING TO EXTRACT THE LAST SIGNIFICANT PARAMETER