# Table to filename mappings for Flibusta DB updates
# Format: table_name=filename.sql.gz

libbook=lib.libbook.sql.gz
libavtor=lib.libavtor.sql.gz
libavtorname=lib.libavtorname.sql.gz
libseq=lib.libseq.sql.gz
libseqname=lib.libseqname.sql.gz
libgenre=lib.libgenre.sql.gz
libgenrelist=lib.libgenrelist.sql.gz
libreviews=lib.reviews.sql.gz
librecs=lib.librecs.sql.gz
librate=lib.librate.sql.gz
libaannotations=lib.a.annotations.sql.gz
libbannotations=lib.b.annotations.sql.gz
libapics=lib.a.annotations_pics.sql.gz
libbpics=lib.b.annotations_pics.sql.gz
libtranslator=lib.libtranslator.sql.gz
# REQUIRED STRING TO EXTRACT THE LAST SIGNIFICANT PARAMETER