"""
Core module for new architecture
"""
from .constants import (
    MAX_BOOKS_SEARCH, MAX_AUTHORS_SEARCH, MAX_SERIES_SEARCH,
    SHOW_POPULAR_ALL_TIME, SHOW_POPULAR_30_DAYS, 
    SHOW_POPULAR_7_DAYS, SHOW_NOVELTY, HEADING_POP,
    SETTING_MAX_BOOKS, SETTING_LANG_SEARCH, SETTING_SIZE_LIMIT,
    SETTING_BOOK_FORMAT, SETTING_SEARCH_TYPE, SETTING_RATING_FILTER,
    SETTING_SEARCH_AREA, SETTING_SEARCH_AREA_B, SETTING_SEARCH_AREA_BA,
    SETTING_SEARCH_AREA_AA, SEARCH_TYPE_BOOKS, SEARCH_TYPE_SERIES,
    SEARCH_TYPE_AUTHORS, BOOK_FORMAT_FB2, BOOK_FORMAT_MOBI,
    BOOK_FORMAT_EPUB, DEFAULT_BOOK_FORMAT, BOOK_RATINGS,
    SETTING_TITLES, SETTING_OPTIONS
)

__all__ = [
    'MAX_BOOKS_SEARCH', 'MAX_AUTHORS_SEARCH', 'MAX_SERIES_SEARCH',
    'SHOW_POPULAR_ALL_TIME', 'SHOW_POPULAR_30_DAYS', 
    'SHOW_POPULAR_7_DAYS', 'SHOW_NOVELTY', 'HEADING_POP',
    'SETTING_MAX_BOOKS', 'SETTING_LANG_SEARCH', 'SETTING_SIZE_LIMIT',
    'SETTING_BOOK_FORMAT', 'SETTING_SEARCH_TYPE', 'SETTING_RATING_FILTER',
    'SETTING_SEARCH_AREA', 'SETTING_SEARCH_AREA_B', 'SETTING_SEARCH_AREA_BA',
    'SETTING_SEARCH_AREA_AA', 'SEARCH_TYPE_BOOKS', 'SEARCH_TYPE_SERIES',
    'SEARCH_TYPE_AUTHORS', 'BOOK_FORMAT_FB2', 'BOOK_FORMAT_MOBI',
    'BOOK_FORMAT_EPUB', 'DEFAULT_BOOK_FORMAT', 'BOOK_RATINGS',
    'SETTING_TITLES', 'SETTING_OPTIONS'
]